version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: social_wires
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data:/data/db
    ports: 
    - "27017:27017"

